### PR TITLE
Updating Dependencies

### PR DESCRIPTION
**Pull request by mportuga**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
@mportuga I'm going to trust you've tested this out. I'm happy to merge this unless @c0bra has any insights.

**Comment by mportuga** [comment]
@JLLeitschuh Don't worry about it. I have been using my own fork in UI-Grid for a while now for this.
https://github.com/angular-ui/ui-grid/blob/master/package.json#L58

**Comment by JLLeitschuh** [comment]
Bahahahaha. Go you!
Maybe this whole bit of infrastructure should be moved under the `angular-ui` team?

**Comment by c0bra** [comment]
I haven't looked at this in years, so I assume anyone knows better than me!

**Comment by mportuga** [comment]
@JLLeitschuh I am actually planning on doing that. I am working on revamping the docs site to be more intuitive and changing this tool to not be as tied to ui-grid as it currently is. Once I am done with that, I will move it under angular-ui and release it to the general public.

**Comment by JLLeitschuh** [comment]
Awesome! Good luck!

**Pull request closed without merging**
